#!/bin/sh

export GOPATH=`pwd`/Godeps/_workspace:$GOPATH

version=`grep currentVersion etcdenv.go | head -n 1 | cut -d\" -f2`

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-linux-amd64-$version .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-darwin-amd64-$version .

hub release create -a etcdenv-linux-amd64-$version -a etcdenv-darwin-amd64-$version v$version

rm etcdenv-*
