#!/bin/sh

export GOPATH=`pwd`/Godeps/_workspace
version=$1

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-linux-amd64-$version .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-darwin-amd64-$version .

hub release create --attach etcdenv-linux-amd64-$version etcdenv-darwin-amd64-$version $version

rm etcdenv-*
