#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 VERSION" >&2
  exit 1
fi

export GOPATH=`pwd`/Godeps/_workspace:$GOPATH

version=$1
sed -i "/const currentVersion/c\const currentVersion = \"$version\"" etcdenv.go
sed -i "/ENV ETCDENV_VERSION/c\ENV ETCDENV_VERSION=$version" Dockerfile

git commit etcdenv.go Dockerfile -m "Release $version"

git tag v$version

GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-linux-amd64-$version .
GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o etcdenv-darwin-amd64-$version .

hub release create -a etcdenv-linux-amd64-$version -a etcdenv-darwin-amd64-$version v$version

rm etcdenv-*
